services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: example
    volumes:
      - ./db/1_init.sql:/docker-entrypoint-initdb.d/init.sql
