services:
  db:
    image: postgres
    restart: always
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: example
      POSTGRES_DB: db
    volumes:
      - ./db/1_init.sql:/docker-entrypoint-initdb.d/init.sql
